// ══════════════════════════════════════════════════════════════════
// PRE-BUILT CKD FOOD DATABASE
// Covers Indian, Italian, Mexican, Chinese, and common foods
// All values per 100g unless noted. Sources: USDA, NHS, renal diet guides
// safetyLevel is for Stage 3/4 CKD — adjust per stage in app logic
// ══════════════════════════════════════════════════════════════════

export const FOOD_DB = {

  // ─── GRAINS & RICE ───────────────────────────────────────────
  "white rice": { foodName:"White Rice (cooked)", safetyLevel:"safe", potassium:35, sodium:1, phosphorus:43, protein:2.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"White rice is one of the best staple foods for CKD. It is low in potassium and phosphorus, making it safe for most stages.", tip:"Always choose white rice over brown rice — brown rice is significantly higher in phosphorus and potassium." },
  "basmati rice": { foodName:"Basmati Rice (cooked)", safetyLevel:"safe", potassium:40, sodium:1, phosphorus:45, protein:2.8, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Basmati rice is excellent for CKD — low potassium, low phosphorus, and easy to digest. A great base for Indian meals.", tip:"Rinse basmati rice 2-3 times before cooking to further reduce starch and any surface minerals." },
  "white bread": { foodName:"White Bread", safetyLevel:"safe", potassium:100, sodium:480, phosphorus:95, protein:8, potassiumRisk:"low", sodiumRisk:"medium", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegetarian", ckdNote:"White bread is acceptable for CKD in moderation. The main concern is sodium — choose low-sodium varieties when possible.", tip:"Choose bread with less than 150mg sodium per slice. Avoid whole wheat bread which has more phosphorus." },
  "chapati": { foodName:"Chapati (white flour)", safetyLevel:"safe", potassium:90, sodium:5, phosphorus:65, protein:4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Chapati made from white flour (maida) is safe for CKD. It is low in potassium and phosphorus.", tip:"Use white flour (maida) instead of whole wheat atta — whole wheat is significantly higher in phosphorus." },
  "white pasta": { foodName:"White Pasta (cooked)", safetyLevel:"safe", potassium:45, sodium:3, phosphorus:58, protein:5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"White pasta is kidney-friendly and a great energy source. Avoid whole wheat pasta which has more phosphorus.", tip:"Cook pasta in unsalted water to keep sodium low. Avoid heavy cheese-based sauces." },
  "poha": { foodName:"Poha (Flattened Rice, cooked)", safetyLevel:"safe", potassium:80, sodium:5, phosphorus:70, protein:2.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Poha is an excellent CKD breakfast — very low in potassium, phosphorus and protein. Light and easy to digest.", tip:"Rinse poha well before cooking to reduce starch. Limit peanuts to just a few as they are high in phosphorus." },
  "semolina": { foodName:"Semolina / Rava (cooked)", safetyLevel:"safe", potassium:85, sodium:5, phosphorus:80, protein:4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Semolina is a kidney-safe grain, ideal for upma and porridge. Low in all four key nutrients.", tip:"Use semolina as a base and add only low-potassium vegetables like cabbage, carrots or peas (small amount)." },
  "corn tortilla": { foodName:"Corn Tortilla", safetyLevel:"safe", potassium:155, sodium:30, phosphorus:95, protein:2.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Corn tortillas are a good CKD choice — lower in sodium and phosphorus than flour tortillas.", tip:"Corn tortillas are preferable to flour tortillas for CKD. Limit to 2-3 per serving." },
  "white flour tortilla": { foodName:"White Flour Tortilla", safetyLevel:"safe", potassium:115, sodium:340, phosphorus:100, protein:5, potassiumRisk:"low", sodiumRisk:"medium", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"White flour tortillas are acceptable for CKD but watch the sodium content. Choose smaller sizes.", tip:"Look for low-sodium tortillas. A single 6-inch tortilla is a reasonable portion." },
  "sushi rice": { foodName:"Sushi Rice (cooked)", safetyLevel:"safe", potassium:40, sodium:120, phosphorus:50, protein:2.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Sushi rice is low in potassium and phosphorus, making it a safe choice for CKD patients.", tip:"The vinegar dressing in sushi rice adds minimal potassium. Keep sodium in check by limiting soy sauce." },

  // ─── LENTILS & LEGUMES ───────────────────────────────────────
  "moong dal": { foodName:"Moong Dal (cooked)", safetyLevel:"caution", potassium:270, sodium:4, phosphorus:150, protein:7, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Moong dal is the most kidney-friendly dal. It has lower potassium and phosphorus than other lentils. Small portions are generally safe for most CKD stages.", tip:"Use a 3:1 rice-to-dal ratio in khichdi. Rinse thoroughly and discard soaking water to reduce potassium and phosphorus." },
  "toor dal": { foodName:"Toor Dal (cooked)", safetyLevel:"caution", potassium:400, sodium:5, phosphorus:200, protein:7, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Toor dal has moderate potassium and phosphorus. Small portions in sambar or dal are usually manageable for Stage 1-3 CKD.", tip:"Always soak toor dal for 4-6 hours and discard water before cooking. Use in small quantities only." },
  "chana dal": { foodName:"Chana Dal (cooked)", safetyLevel:"caution", potassium:350, sodium:5, phosphorus:180, protein:8, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"medium", vegetarianStatus:"vegan", ckdNote:"Chana dal is moderate in potassium and phosphorus. Suitable in small portions for early CKD stages but should be limited in Stage 3-4.", tip:"Soak for 6-8 hours and rinse thoroughly. Limit to 2-3 tbsp cooked per serving." },
  "rajma": { foodName:"Rajma / Kidney Beans (cooked)", safetyLevel:"avoid", potassium:600, sodium:2, phosphorus:250, protein:9, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"high", proteinRisk:"medium", vegetarianStatus:"vegan", ckdNote:"Rajma is very high in potassium and phosphorus, making it risky for CKD patients in Stage 3 and above. It should be avoided or very strictly limited.", tip:"If consuming, soak overnight, boil in fresh water multiple times and use only 2-3 tablespoons. Avoid in Stage 4 and ESRD." },
  "black beans": { foodName:"Black Beans (cooked)", safetyLevel:"avoid", potassium:620, sodium:2, phosphorus:240, protein:9, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"high", proteinRisk:"medium", vegetarianStatus:"vegan", ckdNote:"Black beans are very high in potassium and phosphorus and should be avoided or strictly limited in CKD Stage 3 and beyond.", tip:"Cauliflower or zucchini are excellent kidney-safe substitutes in Mexican dishes that call for black beans." },
  "chickpeas": { foodName:"Chickpeas / Chana (cooked)", safetyLevel:"caution", potassium:290, sodium:7, phosphorus:168, protein:8.9, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"medium", vegetarianStatus:"vegan", ckdNote:"Chickpeas are moderate-high in potassium and phosphorus. A small portion (2-3 tbsp) is manageable for early CKD but should be limited in Stage 3-4.", tip:"Always soak overnight, rinse and boil in fresh water. Limit to 2 tablespoons per serving as part of a balanced CKD meal." },
  "lentils": { foodName:"Lentils (cooked)", safetyLevel:"caution", potassium:370, sodium:4, phosphorus:180, protein:9, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"medium", vegetarianStatus:"vegan", ckdNote:"Lentils have moderate potassium and phosphorus. Small portions are acceptable in early CKD but need restriction in Stage 3-4.", tip:"Soak lentils for 2-4 hours before cooking and discard the water. This reduces potassium by 15-20%." },

  // ─── VEGETABLES ──────────────────────────────────────────────
  "cauliflower": { foodName:"Cauliflower", safetyLevel:"safe", potassium:299, sodium:30, phosphorus:44, protein:1.9, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Cauliflower is one of the most kidney-friendly vegetables. Low in potassium and phosphorus, it is a great substitute for potatoes, rice, or other high-potassium vegetables.", tip:"Use cauliflower to replace potato in aloo gobi, make cauliflower rice, or roast it as a taco filling. It takes on spices beautifully." },
  "cabbage": { foodName:"Cabbage", safetyLevel:"safe", potassium:170, sodium:18, phosphorus:26, protein:1.3, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Cabbage is one of the safest vegetables for CKD. Very low in potassium and phosphorus with good fibre content.", tip:"Use cabbage freely in stir fries, pulav, upma and as a salad base. It can replace higher potassium vegetables in most dishes." },
  "cucumber": { foodName:"Cucumber", safetyLevel:"safe", potassium:147, sodium:2, phosphorus:24, protein:0.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Cucumber is excellent for CKD — very low in all four nutrients of concern. Great for salads and snacking.", tip:"Cucumber is one of the best snack vegetables for CKD. High water content also helps with hydration." },
  "zucchini": { foodName:"Zucchini / Courgette", safetyLevel:"safe", potassium:261, sodium:8, phosphorus:38, protein:1.2, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Zucchini is an excellent CKD-safe vegetable. Use it liberally in Italian dishes, stir fries, or as a potato substitute.", tip:"Zucchini is a great substitute for potatoes in most dishes. It can be sliced, grilled, or added to pasta." },
  "bell pepper": { foodName:"Bell Pepper", safetyLevel:"safe", potassium:211, sodium:4, phosphorus:26, protein:1, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Bell peppers are kidney-friendly with low potassium. They also provide Vitamin C without adding phosphorus burden.", tip:"Use bell peppers to add colour and flavour to dishes instead of tomatoes. Red bell peppers are slightly higher in potassium than green." },
  "onion": { foodName:"Onion", safetyLevel:"safe", potassium:146, sodium:4, phosphorus:29, protein:1.1, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Onions are safe for CKD and a great flavour base for all cuisines. Low in all key nutrients.", tip:"Onions can be used freely as a flavour base in Indian, Italian, Mexican and Chinese cooking." },
  "garlic": { foodName:"Garlic", safetyLevel:"safe", potassium:401, sodium:17, phosphorus:153, protein:6.4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Garlic is safe for CKD in typical cooking amounts (1-3 cloves). The small quantity used means the potassium impact is minimal.", tip:"Use garlic freely for flavour — a typical 1-2 clove serving contributes negligible potassium to your total intake." },
  "ginger": { foodName:"Ginger (fresh)", safetyLevel:"safe", potassium:415, sodium:13, phosphorus:34, protein:1.8, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Fresh ginger is safe for CKD in cooking amounts. It adds wonderful flavour without significant nutrient burden.", tip:"A 1-inch piece of ginger in cooking contributes very little to your daily potassium intake. Use it freely for flavour." },
  "carrot": { foodName:"Carrot", safetyLevel:"safe", potassium:320, sodium:69, phosphorus:35, protein:0.9, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Carrots are safe for CKD in moderate portions. The potassium is low enough for most stages.", tip:"Limit to a small portion (2-3 thin slices per serving) in pulav or stir fry. Boiling carrots and discarding water reduces potassium further." },
  "bottle gourd": { foodName:"Bottle Gourd / Lauki", safetyLevel:"safe", potassium:150, sodium:2, phosphorus:13, protein:0.6, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Bottle gourd is one of the best vegetables for CKD. Extremely low in potassium and phosphorus, it is ideal for Indian cooking.", tip:"Use bottle gourd in dal, sabzi or sambar as a safe, low-potassium vegetable. It is one of the top recommended vegetables for CKD." },
  "ridge gourd": { foodName:"Ridge Gourd / Turai", safetyLevel:"safe", potassium:139, sodium:3, phosphorus:28, protein:0.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Ridge gourd is excellent for CKD — very low in all key nutrients. A great choice for Indian dishes.", tip:"Ridge gourd can be used in sabzi, dal, or as a substitute for higher potassium vegetables in any dish." },
  "bok choy": { foodName:"Bok Choy", safetyLevel:"safe", potassium:252, sodium:65, phosphorus:37, protein:1.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Bok choy is safe for CKD and a great green vegetable for Chinese cooking. Blanching and discarding the water reduces potassium further.", tip:"Blanch bok choy in boiling water for 1-2 minutes and discard the water before stir frying to remove more potassium." },
  "lettuce": { foodName:"Lettuce", safetyLevel:"safe", potassium:194, sodium:28, phosphorus:29, protein:1.4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Lettuce is very safe for CKD. Use it freely as a salad base or in wraps.", tip:"Lettuce and cucumber together make an excellent low-potassium salad base. Add small amounts of low-risk toppings." },
  "spinach": { foodName:"Spinach (raw)", safetyLevel:"avoid", potassium:558, sodium:79, phosphorus:49, protein:2.9, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Spinach is very high in potassium and should be avoided or strictly limited in CKD Stage 3 and beyond. Even small amounts add significant potassium.", tip:"Boiling spinach and discarding the water reduces potassium by about 50%, but it is still considered high risk. Use bok choy or cabbage instead." },
  "tomato": { foodName:"Tomato", safetyLevel:"caution", potassium:237, sodium:5, phosphorus:24, protein:0.9, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Tomatoes are moderate in potassium. A small amount (half a small tomato or 3 cherry tomatoes) is manageable but larger portions should be avoided in Stage 3-4.", tip:"Use red bell pepper as a tomato substitute in cooking — lower potassium with similar colour and flavour." },
  "potato": { foodName:"Potato (boiled)", safetyLevel:"caution", potassium:379, sodium:4, phosphorus:44, protein:2, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Potatoes are high in potassium and need special preparation for CKD. They can be made safer through leaching.", tip:"Peel, dice and boil potatoes in large amounts of water twice (discard water each time) to remove up to 50% of potassium before using." },
  "sweet corn": { foodName:"Sweet Corn", safetyLevel:"caution", potassium:270, sodium:15, phosphorus:89, protein:3.3, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Sweet corn has moderate potassium. Small portions are acceptable but avoid large amounts especially in Stage 3-4.", tip:"Half a cob or 2-3 tablespoons of corn kernels is a reasonable portion for CKD. Avoid canned corn which has added sodium." },
  "mushroom": { foodName:"Mushroom", safetyLevel:"caution", potassium:318, sodium:5, phosphorus:86, protein:3.1, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Mushrooms are moderate in potassium. Small amounts are acceptable in most CKD stages but large portions should be avoided.", tip:"Boil mushrooms and discard the water to reduce potassium before adding to dishes." },
  "peas": { foodName:"Green Peas", safetyLevel:"caution", potassium:244, sodium:5, phosphorus:108, protein:5, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Green peas have moderate potassium and phosphorus. A small portion (2-3 tablespoons) is acceptable but should be limited.", tip:"Use only 2-3 tablespoons of peas per serving. Avoid frozen peas which often have added sodium." },
  "broccoli": { foodName:"Broccoli", safetyLevel:"caution", potassium:316, sodium:33, phosphorus:66, protein:2.8, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Broccoli has moderate potassium. Small portions are acceptable for CKD but it should not be eaten in large amounts.", tip:"Boil broccoli in plenty of water and discard the cooking water to reduce potassium before eating." },
  "banana": { foodName:"Banana", safetyLevel:"avoid", potassium:358, sodium:1, phosphorus:22, protein:1.1, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Bananas are very high in potassium and are one of the most important fruits to avoid in CKD Stage 3 and beyond.", tip:"Choose lower-potassium fruits instead: apple, blueberries, grapes, or pineapple (small portion) are much safer choices." },

  // ─── FRUITS ──────────────────────────────────────────────────
  "apple": { foodName:"Apple", safetyLevel:"safe", potassium:107, sodium:1, phosphorus:11, protein:0.3, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Apples are one of the best fruits for CKD. Low in potassium and phosphorus, they make a great safe snack.", tip:"A medium apple is a safe daily fruit for most CKD stages. Keep the skin on for fibre." },
  "grapes": { foodName:"Grapes", safetyLevel:"safe", potassium:191, sodium:2, phosphorus:20, protein:0.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Grapes are safe for CKD. They are low in potassium and make a good snack in reasonable portions.", tip:"A small bunch (around 15-20 grapes) is a safe CKD portion. Both red and green grapes are equally kidney-friendly." },
  "blueberries": { foodName:"Blueberries", safetyLevel:"safe", potassium:77, sodium:1, phosphorus:12, protein:0.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Blueberries are excellent for CKD — very low in potassium and rich in antioxidants. One of the top recommended fruits.", tip:"A half cup of blueberries is a great CKD snack. They can be added to porridge or eaten fresh." },
  "strawberries": { foodName:"Strawberries", safetyLevel:"safe", potassium:153, sodium:1, phosphorus:24, protein:0.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Strawberries are safe for CKD. Moderately low in potassium and a good source of Vitamin C.", tip:"Half a cup of fresh strawberries is a safe CKD portion. Avoid strawberry jams or preserves due to high sugar content." },
  "watermelon": { foodName:"Watermelon", safetyLevel:"caution", potassium:112, sodium:1, phosphorus:11, protein:0.6, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Watermelon is low in potassium per 100g but the large portion sizes people typically eat mean total potassium can add up.", tip:"Limit to a 1-cup serving. The low potassium per 100g is misleading because people tend to eat large amounts." },
  "pineapple": { foodName:"Pineapple", safetyLevel:"safe", potassium:109, sodium:1, phosphorus:8, protein:0.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Pineapple is one of the best fruits for CKD. Very low in potassium and phosphorus.", tip:"Fresh pineapple is preferable to canned. A half cup portion is safe for most CKD stages." },
  "avocado": { foodName:"Avocado", safetyLevel:"caution", potassium:485, sodium:7, phosphorus:52, protein:2, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Avocado is high in potassium and should be limited in CKD Stage 3-4. A very small amount (2-3 thin slices) can be used occasionally.", tip:"In sushi or salads, limit to 2-3 thin slices per serving. Avoid guacamole which uses large amounts." },
  "mango": { foodName:"Mango", safetyLevel:"caution", potassium:168, sodium:1, phosphorus:14, protein:0.8, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Mango has moderate potassium. A small portion is acceptable but larger amounts can push potassium intake up.", tip:"Limit to half a small mango or about 80g per serving. Raw mango (kacchi keri) in small amounts is also acceptable." },

  // ─── DAIRY & EGGS ────────────────────────────────────────────
  "paneer": { foodName:"Paneer", safetyLevel:"caution", potassium:160, sodium:28, phosphorus:490, protein:18, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"high", proteinRisk:"high", vegetarianStatus:"vegetarian", ckdNote:"Paneer is very high in phosphorus and protein, making it problematic for CKD Stage 3 and beyond. Small portions only.", tip:"Limit paneer to 30-40g (small cube) per serving, once or twice per week at most. Tofu is a lower-phosphorus alternative." },
  "egg": { foodName:"Egg (whole)", safetyLevel:"caution", potassium:138, sodium:142, phosphorus:198, protein:13, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"medium", vegetarianStatus:"vegetarian", ckdNote:"Eggs are moderate in phosphorus and protein. One egg per day is generally acceptable for most CKD stages, but limit to egg whites if protein restriction is needed.", tip:"One egg per serving maximum. Egg whites have much less phosphorus than whole eggs — use 2 egg whites in place of 1 whole egg to reduce phosphorus." },
  "milk": { foodName:"Milk (whole)", safetyLevel:"caution", potassium:150, sodium:44, phosphorus:93, protein:3.4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegetarian", ckdNote:"Milk has moderate phosphorus. Half a cup per day is usually acceptable but larger amounts can contribute significantly to phosphorus intake.", tip:"Limit to half a cup (120ml) per day. Rice milk or coconut milk are lower-phosphorus alternatives for cooking." },
  "curd": { foodName:"Curd / Yogurt (plain)", safetyLevel:"caution", potassium:141, sodium:36, phosphorus:104, protein:3.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegetarian", ckdNote:"Curd/yogurt has moderate phosphorus. A small portion (3-4 tablespoons) as raita is generally acceptable for most CKD stages.", tip:"Limit curd to 3-4 tablespoons per serving. Mix with cucumber for raita — a kidney-safe combination." },
  "mozzarella": { foodName:"Mozzarella Cheese", safetyLevel:"caution", potassium:95, sodium:627, phosphorus:354, protein:22, potassiumRisk:"low", sodiumRisk:"high", phosphorusRisk:"high", proteinRisk:"high", vegetarianStatus:"vegetarian", ckdNote:"Mozzarella is high in phosphorus, protein and sodium. Use in very small amounts as a topping, not as a main ingredient.", tip:"Limit to 30g (1 oz) maximum per serving. Fresh mozzarella has slightly less sodium than processed. Avoid regular cheese entirely." },

  // ─── PROTEINS ────────────────────────────────────────────────
  "tofu": { foodName:"Tofu (firm)", safetyLevel:"safe", potassium:150, sodium:14, phosphorus:97, protein:8, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Tofu is a great CKD-friendly protein source. The phosphorus in tofu is plant-based and less well absorbed by the body than animal phosphorus.", tip:"Tofu prepared without salt is one of the best protein sources for CKD. Calcium-set tofu has more calcium but similar phosphorus levels." },

  // ─── OILS & FATS ─────────────────────────────────────────────
  "ghee": { foodName:"Ghee", safetyLevel:"safe", potassium:5, sodium:2, phosphorus:3, protein:0.1, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegetarian", ckdNote:"Ghee is safe for CKD in small amounts. It adds energy and flavour without adding potassium or phosphorus.", tip:"1-2 teaspoons of ghee per meal is acceptable. It is a good energy source for CKD patients who need to maintain weight." },
  "olive oil": { foodName:"Olive Oil", safetyLevel:"safe", potassium:1, sodium:2, phosphorus:0, protein:0, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Olive oil is excellent for CKD — zero potassium, phosphorus and protein. A healthy fat source for cooking.", tip:"Use olive oil freely for cooking and dressings. It is one of the most kidney-safe cooking fats." },
  "coconut oil": { foodName:"Coconut Oil", safetyLevel:"safe", potassium:0, sodium:0, phosphorus:0, protein:0, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Coconut oil is safe for CKD. Like all oils it has zero potassium and phosphorus.", tip:"Use in moderate amounts as a cooking oil. Coconut milk however has potassium so use sparingly in cooking." },

  // ─── SPICES & HERBS ──────────────────────────────────────────
  "turmeric": { foodName:"Turmeric", safetyLevel:"safe", potassium:2525, sodium:38, phosphorus:299, protein:9.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Turmeric is safe for CKD in cooking amounts. The very small quantities used (0.5-1 tsp) make the absolute potassium contribution negligible.", tip:"Use turmeric freely in cooking. Studies suggest it may have anti-inflammatory benefits which could help CKD management." },
  "cumin": { foodName:"Cumin / Jeera", safetyLevel:"safe", potassium:1788, sodium:168, phosphorus:499, protein:17.8, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Cumin is safe in cooking amounts. The tiny quantity used per dish means negligible nutrient contribution.", tip:"Use cumin seeds and powder freely in Indian cooking — tempering with jeera adds flavour without kidney risk." },
  "coriander powder": { foodName:"Coriander Powder", safetyLevel:"safe", potassium:1267, sodium:35, phosphorus:409, protein:12.4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Coriander powder is safe in typical cooking amounts. A teaspoon in a dish for 4 servings contributes minimal potassium.", tip:"Use coriander powder freely to add flavour to Indian dishes. Fresh coriander leaves are also safe as garnish." },
  "fresh mint": { foodName:"Fresh Mint Leaves", safetyLevel:"safe", potassium:569, sodium:31, phosphorus:73, protein:3.3, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Fresh mint is safe for CKD in cooking amounts. Used as garnish or in pulav, the contribution to potassium is negligible.", tip:"Add fresh mint to pulav, raita, or as garnish. It adds wonderful aroma and freshness without any kidney risk in small amounts." },

  // ─── COMMON DISHES ───────────────────────────────────────────
  "khichdi": { foodName:"Khichdi (rice + moong dal)", safetyLevel:"safe", potassium:200, sodium:120, phosphorus:115, protein:6, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Khichdi is one of the most kidney-safe Indian meals. The combination of white rice and small amounts of moong dal makes it ideal for CKD.", tip:"Use a 3:1 ratio of rice to dal. Season lightly with turmeric, cumin and a small amount of salt or use no salt at all." },
  "upma": { foodName:"Upma (semolina)", safetyLevel:"safe", potassium:190, sodium:130, phosphorus:90, protein:4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Upma made with semolina and low-potassium vegetables is an excellent CKD breakfast option.", tip:"Add only kidney-safe vegetables like cabbage, carrots (small portion) or bottle gourd. Avoid tomatoes and potatoes." },
  "poha dish": { foodName:"Poha Dish (cooked, with vegetables)", safetyLevel:"safe", potassium:160, sodium:110, phosphorus:80, protein:3, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Poha dish is an excellent CKD-friendly breakfast. The flattened rice base is low in all key nutrients.", tip:"Rinse poha well, add onion, green chilli and mustard seeds. Limit peanuts to a few as garnish only." },
  "idli": { foodName:"Idli (steamed)", safetyLevel:"safe", potassium:75, sodium:200, phosphorus:55, protein:2.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Idli is a safe CKD breakfast — steamed rice and lentil cakes that are low in potassium. The main concern is sodium from batter fermentation.", tip:"Limit to 2-3 idlis per serving. Pair with a modified low-potassium sambar using bottle gourd instead of drumstick." },
  "dosa": { foodName:"Plain Dosa", safetyLevel:"safe", potassium:80, sodium:220, phosphorus:60, protein:2.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Plain dosa is safe for CKD. Avoid masala dosa filling (potato) which adds significant potassium.", tip:"Stick to plain dosa without potato filling. Pair with coconut chutney (small amount) rather than tomato-based chutneys." },
  "pasta aglio e olio": { foodName:"Pasta Aglio e Olio", safetyLevel:"safe", potassium:130, sodium:85, phosphorus:90, protein:7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"This simple garlic and olive oil pasta is one of the most kidney-safe Italian dishes. No tomato sauce means low potassium.", tip:"Use white pasta and season lightly. Add parsley and chilli flakes for flavour without kidney risk." },
  "congee": { foodName:"Congee (Rice Porridge)", safetyLevel:"safe", potassium:65, sodium:20, phosphorus:35, protein:2, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Congee is one of the most kidney-friendly foods. The high water content dilutes all nutrients significantly.", tip:"Cook 1 part rice to 8-10 parts water for proper congee. Season with only a small piece of ginger and a few drops of sesame oil." },
  "cauliflower tacos": { foodName:"Cauliflower Tacos", safetyLevel:"safe", potassium:210, sodium:95, phosphorus:82, protein:4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Cauliflower tacos are an excellent CKD-safe Mexican alternative to bean tacos. All the flavour, kidney-safe ingredients.", tip:"Roast cauliflower with cumin, paprika and a little oil. Serve in corn tortillas with shredded cabbage and a squeeze of lime." },
  "veggie sushi": { foodName:"Vegetable Sushi Rolls", safetyLevel:"safe", potassium:185, sodium:150, phosphorus:82, protein:4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Vegetable sushi with cucumber is very kidney-safe. The main risk is soy sauce — always use low-sodium and limit to 1 tsp.", tip:"Cucumber rolls are the safest. Limit avocado to 2-3 thin slices. Always use low-sodium soy sauce, max 1 tsp dipping." },
  "hummus": { foodName:"Hummus", safetyLevel:"caution", potassium:228, sodium:379, phosphorus:176, protein:7.9, potassiumRisk:"medium", sodiumRisk:"high", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Hummus is moderate-high in phosphorus and sodium. Small portions (2 tablespoons) as an occasional dip are acceptable but should not be a daily staple.", tip:"Limit to 2 tablespoons per serving maximum. Pair with cucumber or bell pepper strips, not with high-potassium vegetables." },
  "white rice cooked": { foodName:"White Rice (cooked)", safetyLevel:"safe", potassium:35, sodium:1, phosphorus:43, protein:2.7, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"White rice is one of the best staple foods for CKD. Safe for all stages.", tip:"Cook without salt. Pair with kidney-safe vegetables and small portions of dal or tofu." },
  "dal": { foodName:"Dal (mixed, cooked)", safetyLevel:"caution", potassium:300, sodium:5, phosphorus:160, protein:7, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Dal is moderate in potassium and phosphorus. Small portions with plenty of rice are generally acceptable for CKD Stage 1-3.", tip:"Soak dal for 4-6 hours before cooking and discard the soaking water. Use moong dal as your first choice — it is the most kidney-friendly." },
  "raita": { foodName:"Raita (curd + cucumber)", safetyLevel:"caution", potassium:160, sodium:40, phosphorus:95, protein:2.5, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"medium", proteinRisk:"low", vegetarianStatus:"vegetarian", ckdNote:"Raita in small amounts is acceptable for CKD. Cucumber-based raita is safer than tomato or onion raita.", tip:"Limit to 3-4 tablespoons per meal. Use cucumber raita rather than tomato or mixed vegetable raita." },
  "sambar": { foodName:"Sambar (modified, low-K)", safetyLevel:"caution", potassium:220, sodium:180, phosphorus:110, protein:4, potassiumRisk:"medium", sodiumRisk:"medium", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Traditional sambar has high-potassium ingredients. A modified version using bottle gourd and avoiding tamarind and tomatoes is much safer.", tip:"Make sambar with bottle gourd instead of drumstick. Replace tamarind with a small squeeze of lemon and skip tomatoes." },

  // ─── SNACKS & OTHERS ─────────────────────────────────────────
  "peanuts": { foodName:"Peanuts", safetyLevel:"caution", potassium:705, sodium:18, phosphorus:376, protein:25.8, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"high", proteinRisk:"high", vegetarianStatus:"vegan", ckdNote:"Peanuts are very high in phosphorus, potassium and protein. They should be used only as a small garnish (4-5 peanuts) in CKD.", tip:"Use only 4-5 peanuts as a garnish in poha or upma. Avoid peanut butter and peanut-based snacks entirely." },
  "tahini": { foodName:"Tahini (sesame paste)", safetyLevel:"caution", potassium:414, sodium:115, phosphorus:592, protein:17, potassiumRisk:"medium", sodiumRisk:"low", phosphorusRisk:"high", proteinRisk:"high", vegetarianStatus:"vegan", ckdNote:"Tahini is high in phosphorus. Use only 1-2 teaspoons in hummus or dressings.", tip:"Limit tahini to 1 teaspoon per serving maximum. The phosphorus content is significant even in small amounts." },
  "nori": { foodName:"Nori (seaweed sheets)", safetyLevel:"safe", potassium:356, sodium:48, phosphorus:58, protein:5.8, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Nori used in sushi (1-2 sheets) contributes minimal potassium and is safe for CKD.", tip:"Use 1-2 nori sheets per sushi roll. The quantities used in normal sushi making do not pose a kidney risk." },
  "lime juice": { foodName:"Lime Juice (fresh)", safetyLevel:"safe", potassium:102, sodium:2, phosphorus:18, protein:0.4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Fresh lime juice is safe for CKD in cooking amounts. A squeeze of lime adds flavour without significant potassium.", tip:"Use lime juice as a salt substitute — it adds bright flavour without sodium. A squeeze over food is very safe for CKD." },
  "lemon juice": { foodName:"Lemon Juice (fresh)", safetyLevel:"safe", potassium:103, sodium:1, phosphorus:16, protein:0.4, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Fresh lemon juice is safe for CKD in cooking amounts. An excellent low-sodium flavour enhancer.", tip:"Use lemon juice to replace salt and tamarind in Indian cooking. It is one of the best CKD-friendly flavour enhancers." },
  "sesame oil": { foodName:"Sesame Oil", safetyLevel:"safe", potassium:0, sodium:0, phosphorus:0, protein:0, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Sesame oil is safe for CKD in small amounts as a finishing oil. Zero potassium and phosphorus.", tip:"Use just a few drops of sesame oil as a finishing touch in Chinese dishes. A little goes a long way for flavour." },
  "low sodium soy sauce": { foodName:"Low-Sodium Soy Sauce", safetyLevel:"caution", potassium:356, sodium:2680, phosphorus:130, protein:9.3, potassiumRisk:"medium", sodiumRisk:"high", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Even low-sodium soy sauce is high in sodium. Limit strictly to 1 teaspoon per serving.", tip:"Always use low-sodium soy sauce and never more than 1 teaspoon at a time. Regular soy sauce has almost double the sodium." },
  "soy sauce": { foodName:"Regular Soy Sauce", safetyLevel:"avoid", potassium:435, sodium:5720, phosphorus:130, protein:10.5, potassiumRisk:"medium", sodiumRisk:"high", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Regular soy sauce is extremely high in sodium and should be avoided entirely in CKD. Always choose low-sodium alternatives.", tip:"Switch to low-sodium soy sauce immediately. Use maximum 1 teaspoon even of the low-sodium version." },
  "salt": { foodName:"Table Salt", safetyLevel:"caution", potassium:8, sodium:38758, phosphorus:0, protein:0, potassiumRisk:"low", sodiumRisk:"high", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Salt is the primary sodium source and must be strictly limited in CKD. Use the minimum possible and try salt-free flavouring alternatives.", tip:"Use lemon juice, lime, ginger, garlic and spices to flavour food instead of salt. Target less than 1/4 teaspoon total salt per day." },

  // ─── PIZZA / ITALIAN SPECIFICS ───────────────────────────────
  "pizza dough": { foodName:"Pizza Dough (white flour)", safetyLevel:"safe", potassium:100, sodium:310, phosphorus:80, protein:7, potassiumRisk:"low", sodiumRisk:"medium", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Plain pizza dough is acceptable for CKD. The main concern is sodium from the dough itself.", tip:"Choose thin crust to reduce the overall sodium from the dough. Making homemade dough without salt is even better." },
  "tomato sauce": { foodName:"Tomato Sauce (pizza/pasta)", safetyLevel:"caution", potassium:400, sodium:430, phosphorus:35, protein:1.7, potassiumRisk:"medium", sodiumRisk:"high", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Tomato sauce is moderate-high in potassium and can be high in sodium. Use sparingly as a thin spread only.", tip:"Use no more than 2 tablespoons of tomato sauce per pizza or pasta serving. Look for low-sodium versions." },

  // ─── BEVERAGES ───────────────────────────────────────────────
  "green tea": { foodName:"Green Tea", safetyLevel:"safe", potassium:20, sodium:1, phosphorus:1, protein:0, potassiumRisk:"low", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Green tea is safe for CKD in moderate amounts. It is low in potassium and phosphorus.", tip:"1-2 cups of green tea per day is generally safe for CKD. Avoid green tea extract supplements which can be harmful." },
  "coconut water": { foodName:"Coconut Water", safetyLevel:"avoid", potassium:250, sodium:105, phosphorus:20, protein:0.7, potassiumRisk:"high", sodiumRisk:"low", phosphorusRisk:"low", proteinRisk:"low", vegetarianStatus:"vegan", ckdNote:"Coconut water is very high in potassium and should be avoided in CKD Stage 3 and beyond. It is often mistakenly thought to be healthy for everyone.", tip:"Avoid coconut water entirely in CKD Stage 3-ESRD. Plain water is always the safest beverage choice." },
};

// Lookup function — tries exact match, then partial match
export function lookupFood(query) {
  if (!query) return null;
  const q = query.toLowerCase().trim();

  // Try exact match first
  if (FOOD_DB[q]) return FOOD_DB[q];

  // Try partial match — query contains key or key contains query
  const keys = Object.keys(FOOD_DB);
  const match = keys.find(k => q.includes(k) || k.includes(q));
  if (match) return FOOD_DB[match];

  // Try word-by-word match
  const words = q.split(/\s+/);
  const wordMatch = keys.find(k => words.some(w => w.length > 3 && k.includes(w)));
  if (wordMatch) return FOOD_DB[wordMatch];

  return null; // Not found — will fall through to API
}
